@extends('layouts.admin')
@section('title', 'Footer Settings')
@section('content')
<div class="page-header-premium"><div><h4><i class="fa-solid fa-window-maximize me-2"></i>Footer Settings</h4><p>Manage the public footer CTA, links and social profiles</p></div></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form action="{{ route('footer-settings.update') }}" method="POST">@csrf @method('PUT')
<div class="card card-premium mb-4"><div class="card-header bg-white pt-4 border-0"><h6 class="fw-bold text-primary">CTA Banner & Brand Text</h6></div><div class="card-body"><div class="row g-3"><div class="col-12"><label class="form-label">Footer Description</label><textarea name="description" class="form-control" rows="3" required>{{ old('description', $footer['description']) }}</textarea></div><div class="col-md-6"><label class="form-label">CTA Title</label><input name="cta_title" class="form-control" value="{{ old('cta_title', $footer['cta_title']) }}" required></div><div class="col-md-6"><label class="form-label">CTA Button Text</label><input name="cta_button_text" class="form-control" value="{{ old('cta_button_text', $footer['cta_button_text']) }}" required></div><div class="col-12"><label class="form-label">CTA Description</label><textarea name="cta_description" class="form-control" rows="2" required>{{ old('cta_description', $footer['cta_description']) }}</textarea></div><div class="col-12"><label class="form-label">CTA Button Link</label><input name="cta_button_link" class="form-control" value="{{ old('cta_button_link', $footer['cta_button_link']) }}" required></div></div></div></div>
<div class="row g-4"><div class="col-lg-5"><div class="card card-premium h-100"><div class="card-header bg-white pt-4 border-0"><h6 class="fw-bold">Social Links</h6></div><div class="card-body">@for($i=0;$i<4;$i++)<div class="border rounded p-3 mb-3"><div class="row g-2"><div class="col-4"><input name="socials[{{ $i }}][name]" class="form-control" value="{{ old('socials.'.$i.'.name', $footer['socials'][$i]['name']) }}" required></div><div class="col-4"><input name="socials[{{ $i }}][icon]" class="form-control" value="{{ old('socials.'.$i.'.icon', $footer['socials'][$i]['icon']) }}" required></div><div class="col-4"><input name="socials[{{ $i }}][url]" class="form-control" value="{{ old('socials.'.$i.'.url', $footer['socials'][$i]['url']) }}" placeholder="URL"></div></div></div>@endfor</div></div></div><div class="col-lg-7"><div class="card card-premium h-100"><div class="card-header bg-white pt-4 border-0"><h6 class="fw-bold">Footer Links</h6></div><div class="card-body"><label class="form-label">Quick Links</label>@for($i=0;$i<5;$i++)<div class="row g-2 mb-2"><div class="col-6"><input name="quick_links[{{ $i }}][label]" class="form-control" value="{{ old('quick_links.'.$i.'.label', $footer['quick_links'][$i]['label']) }}" required></div><div class="col-6"><input name="quick_links[{{ $i }}][url]" class="form-control" value="{{ old('quick_links.'.$i.'.url', $footer['quick_links'][$i]['url']) }}" required></div></div>@endfor<label class="form-label mt-3">Service Links</label>@for($i=0;$i<5;$i++)<div class="row g-2 mb-2"><div class="col-6"><input name="service_links[{{ $i }}][label]" class="form-control" value="{{ old('service_links.'.$i.'.label', $footer['service_links'][$i]['label']) }}" required></div><div class="col-6"><input name="service_links[{{ $i }}][url]" class="form-control" value="{{ old('service_links.'.$i.'.url', $footer['service_links'][$i]['url']) }}" required></div></div>@endfor</div></div></div></div><div class="text-end mt-4"><button class="btn btn-primary"><i class="fa-solid fa-save me-1"></i>Save Footer Settings</button></div></form>
@endsection
