@extends('layouts.admin')

@section('title', 'Packages')

@section('content')
<div class="page-header-premium d-flex justify-content-between align-items-center"><div><h4><i class="fa-solid fa-box-open me-2"></i>Health Packages</h4><p>Manage the packages shown on the public Packages page</p></div><a href="{{ route('admin-packages.create') }}" class="btn btn-premium-new"><i class="fa-solid fa-plus me-2"></i>Add Package</a></div>
@if(session('success'))<div class="alert alert-success alert-dismissible fade show border-0 shadow-sm rounded-3 mb-4">{{ session('success') }}<button type="button" class="btn-close" data-bs-dismiss="alert"></button></div>@endif
<div class="card-premium card"><div class="table-responsive"><table class="table table-premium mb-0"><thead><tr><th>Image</th><th>Package</th><th>Price</th><th>Tests</th><th>Status</th><th class="text-center">Actions</th></tr></thead><tbody>
@forelse($packages as $package)<tr><td>@if($package->image)<img src="{{ asset('storage/'.$package->image) }}" alt="{{ $package->name }}" style="width:80px;height:52px;object-fit:cover;border-radius:8px;">@else<div class="bg-light text-primary d-flex align-items-center justify-content-center" style="width:80px;height:52px;border-radius:8px;"><i class="fa-solid fa-box-open"></i></div>@endif</td><td><span class="fw-semibold">{{ $package->name }}</span><br><small class="text-muted">{{ Str::limit($package->description, 70) }}</small></td><td>৳ {{ number_format($package->discount_price ?? $package->price, 2) }} @if($package->discount_price)<br><small class="text-muted text-decoration-line-through">৳ {{ number_format($package->price, 2) }}</small>@endif</td><td>{{ $package->tests_count }}</td><td><span class="status-pill {{ $package->status === 'active' ? 'pill-success' : 'pill-danger' }}">{{ ucfirst($package->status) }}</span></td><td><div class="d-flex justify-content-center gap-2"><a href="{{ route('admin-packages.edit', $package) }}" class="action-btn action-btn-edit"><i class="fa-solid fa-pen"></i></a><form action="{{ route('admin-packages.destroy', $package) }}" method="POST" onsubmit="return confirm('Delete this package?');">@csrf @method('DELETE')<button class="action-btn action-btn-del"><i class="fa-solid fa-trash"></i></button></form></div></td></tr>@empty<tr><td colspan="6"><div class="empty-state"><i class="fa-solid fa-box-open"></i><strong>No packages found</strong></div></td></tr>@endforelse
</tbody></table></div>@if($packages->hasPages())<div class="px-4 py-3 border-top">{{ $packages->links() }}</div>@endif</div>
@endsection
