@extends('layouts.admin')
@section('title', 'Contact Page')
@section('content')
<div class="page-header-premium"><div><h4><i class="fa-solid fa-address-card me-2"></i>Contact Page</h4><p>Manage contact details, map and working hours</p></div></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form action="{{ route('contact-page.update') }}" method="POST">@csrf @method('PUT')
<div class="card card-premium mb-4"><div class="card-header bg-white pt-4 border-0"><h6 class="fw-bold text-primary">Contact Information</h6></div><div class="card-body"><div class="row g-3"><div class="col-12"><label class="form-label">Address</label><textarea name="address" class="form-control" rows="2" required>{{ old('address', $content['address']) }}</textarea></div><div class="col-md-6"><label class="form-label">Emergency Phone</label><input name="emergency_phone" class="form-control" value="{{ old('emergency_phone', $content['emergency_phone']) }}" required></div><div class="col-md-6"><label class="form-label">Appointment Phone</label><input name="appointment_phone" class="form-control" value="{{ old('appointment_phone', $content['appointment_phone']) }}" required></div><div class="col-md-6"><label class="form-label">General Email</label><input type="email" name="general_email" class="form-control" value="{{ old('general_email', $content['general_email']) }}" required></div><div class="col-md-6"><label class="form-label">Report Email</label><input type="email" name="report_email" class="form-control" value="{{ old('report_email', $content['report_email']) }}" required></div><div class="col-12"><label class="form-label">Google Map Embed URL</label><input name="map_url" class="form-control" value="{{ old('map_url', $content['map_url']) }}" placeholder="https://www.google.com/maps/embed?..." required></div></div></div></div>
<div class="card card-premium mb-4"><div class="card-header bg-white pt-4 border-0"><h6 class="fw-bold text-secondary">Working Hours</h6></div><div class="card-body"><div class="row g-3">@for($i=0;$i<4;$i++)<div class="col-md-6"><div class="border rounded p-3"><label class="form-label">Label</label><input name="hours[{{ $i }}][label]" class="form-control mb-2" value="{{ old('hours.'.$i.'.label', $content['hours'][$i]['label'] ?? '') }}" required><label class="form-label">Time</label><input name="hours[{{ $i }}][time]" class="form-control" value="{{ old('hours.'.$i.'.time', $content['hours'][$i]['time'] ?? '') }}" required></div></div>@endfor</div></div></div><div class="text-end mb-4"><button class="btn btn-primary"><i class="fa-solid fa-save me-1"></i>Save Contact Page</button></div></form>
@endsection
